version: "3"

services:
  webapp:
    restart: unless-stopped
    ports:
      - "8001:80"

  api:
    restart: unless-stopped
  apidb:
    restart: unless-stopped

  auth:
    restart: unless-stopped
  authdb:
    restart: unless-stopped
